name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: ./gradlew assemble

      - name: Test
        run: ./gradlew test
